version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  backend:
    build: ./task-backend
    container_name: task-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongodb:27017
    depends_on:
      - mongodb

  frontend:
    build: ./task-frontend
    container_name: task-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
